### ISSUE TITLE
Project's attribute "pname" should be a describing attribute with type prepend

### ISSUE THREAD

**Issue by wholton** [sqltutor-project/sqltutor#19]
Query: SELECT plocation FROM project WHERE pname = 'ProductX' AND dnum = 5;

Translation: Select the location of each project where its name is "ProductX" and its controlling department's number is 5

This should say: "Select the location of the ProductX project where it's controlling department's number is 5."

Even if we didn't say "ProductX project", because pname is the primary key we should say something like "Select the location of the project with the name ProductX where its controlling department's number is 5."

**Comment by jakecobb** [comment]
Isn't this just a matter of marking pname as a describing attribute with type prepend?  Or is there a problem with that rule not applying?  I wouldn't call this translation incorrect.

**Comment by wholton** [comment]
Yes, you're right. That's basically what I was saying here, but I should have just put as much in the title. The second part is to say: what if this wasn't a describing attribute? Wouldn't the translation be wrong? Basically, because we're no we're constraining it to a single project, we should say "the project" instead of "of each", right?

**Comment by jakecobb** [comment]
I see.  I still wouldn't call it wrong exactly, but it would be a better
translation to say "the project".  I suppose the condition should be that
if an entity's key is restricted to exactly one value, then the cardinality
should be 1.  On top of that, lowering rules need to respect the
cardinality.

**Comment by wholton** [comment]
Added appended attribute to department number. Added prepend to project name. Determiner is now not applied when targeting a table entity appended by a describing attribute. 

New Translation: "Select the location of the ProductX project where department 5 controls the ProductX project."
