### ISSUE TITLE
ViewExpiredException on redeploys

### ISSUE THREAD

**Issue by jakecobb** [sqltutor-project/sqltutor#22]
View state is not restored after a redeploy, causing functionality to break.  The result is a `ViewExpiredException` that is visible on page loads and silently breaks AJAX requests.

**Comment by wholton** [comment]
Stackoverflow had a post about this, and people seemed to be mentioning the fact, unless you specify a key in the web.xml, redeploying creates a new key (and therefore can't decrypted the old session).

An alternative answer was that not everything was being serialized properly.

**Comment by jakecobb** [comment]
I fixed the serialization issues several days ago.  I've tried basically everything else recommended already (uncommitted) but it hasn't helped.  Opened my own question [here](https://stackoverflow.com/questions/26592310/preventing-viewexpiredexception-with-jsf-2-after-redeploy).

**Comment by jakecobb** [comment]
This may be related: https://issues.apache.org/bugzilla/show_bug.cgi?id=46924

**Comment by jakecobb** [comment]
Serialization and reuse across Tomcat restarts are fixed by 7292af05a8b8f74.  It seems that losing sessions is a "feature" of Tomcat when deploying via WAR file.   We have to copy an unpacked directory to avoid losing the sessions, because WAR changes cause an `undeploy` followed by a `deploy`, as opposed to a `reload`.

The bug report linked above states:

> There are ways to achieve an update to an application without dropping the sessions. The simplest is probably:
> - deploy as an exploded directory rather than a WAR
> - update the files
> - touch web.xml to trigger a reload
> 
> The reason for the current behaviour is to prevent problems when WARs are updated in incompatible ways and anything other than a full undeploy followed by (essentially) a new deployment causes conflicts.

This is still the case in the [current Tomcat 7.0 documentation](https://tomcat.apache.org/tomcat-7.0-doc/manager-howto.html):

> Currently, application reloading (to pick up changes to the classes or web.xml file) is not supported when a web application is deployed directly from a WAR file. It only works when the web application is deployed from an unpacked directory.
