### ISSUE TITLE
WHERE CLAUSE not working 100% correctly

### ISSUE THREAD

**Issue by ylee318** [sqltutor-project/sqltutor#34]
When I am performing Navathe problem 6, the where clause keeps treating my where clause as like this:
where someAttribute = "value"
incorrect. Your query was malformed. Please try again. ERROR: column "value" does not exist Position: 65
       (sorry, natural language feedback temporarily disabled) 
This doesn't make sense.

**Comment by ylee318** [comment]
It now works all of a sudden. I don't know why.

**Comment by jakecobb** [comment]
You need to use single-quotes `'` for strings, double-quotes `"` are for identifiers.  You can see the [Postgresql documentation](http://www.postgresql.org/docs/9.1/static/sql-syntax-lexical.html) for information about this.

**Comment by wholton** [comment]
Use single quotes. Using double quotes here makes the Postgres engine think that you're talking about a column (it uses double quotes to differentiate between columns which have different casing, e.g. department is equivalent to DePaRtMeNt, but is not equivalent to "DePaRtMeNt").

For more information, see 4.1.2.1 (String Constants):
http://www.postgresql.org/docs/9.1/static/sql-syntax-lexical.html

**Comment by jakecobb** [comment]
Well we gave basically the same answer at the same time, but for future reference:
Section 4.1.1 is also relevant.  This behavior is also dictated by the standard, SQL 99 gives the grammar:

```
<delimited identifier> ::=
    <double quote> <delimited identifier body> <double quote>
```
